### ISSUE TITLE
Failing tests on Arch Linux

### ISSUE THREAD

**Issue by shibumi** [JoeLametta/whipper#226]
Hey,
I get failing tests when I build whipper in a clean environment: (version 0.6.0)
```
...................ERROR:whipper.common.accurip:no track AR CRC on non-HTOA track 1
.......ERROR:whipper.common.accurip:could not save entry to /tmp/tmpug3ECRwhipper_accurip_cache_test/c/1/2/dBAR-002-0000f21c-00027ef8-05021002.bin: "[Errno 13]
 Permission denied: '/tmp/tmpug3ECRwhipper_accurip_cache_test/c'"
.ERROR:whipper.common.accurip:error retrieving AccurateRip entry: 404 Not Found <Response [404]>
WARNING:whipper.common.accurip:entry not found in AccurateRip database
...WARNING:whipper.program.arc:ARC calculation failed: arc return code is non zero: 1
ERROR:whipper.common.accurip:could not calculate AccurateRip v1 checksum for track 1 '/does/not/exist'
WARNING:whipper.program.arc:ARC calculation failed: arc return code is non zero: 1
ERROR:whipper.common.accurip:could not calculate AccurateRip v2 checksum for track 1 '/does/not/exist'
..........................................................WARNING:whipper.program.cdrdao:cdrdao version detection failed: could not find version
F..WARNING:whipper.common.mbngs:Release with ID '3451f29c-9bb8-4cc5-bfcc-bd50104b94f8' (Jeff Buckley - Everybody Here Wants You) does not have a date
...............
======================================================================
FAIL: testGetVersion (whipper.test.test_program_cdrdao.VersionTestCase)
testGetVersion
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
    reraise(exc_info[1], exc_info[2])
  File "/usr/lib/python2.7/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/build/whipper/src/whipper-0.6.0/whipper/test/test_program_cdrdao.py", line 13, in testGetVersion
    self.failUnless(v)
  File "/usr/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 395, in assertTrue
    super(_Assertions, self).assertTrue(condition, msg)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
FailTest: None is not true

----------------------------------------------------------------------
Ran 106 tests in 6.746s

FAILED (failures=1)
```

Any Idea? whipper runs.. I just don't like failing tests.

**Comment by JoeLametta** [comment]
> Hey,
> I get failing tests when I build whipper in a clean environment: (version 0.6.0)

Hi, thanks for the issue report.

> Any Idea? whipper runs.. I just don't like failing tests.

I think the fail is still caused by [this one](https://github.com/JoeLametta/whipper/issues/157#issuecomment-322018317) (which whipper can't do anything about). Please check and let me know what's the outcome.

Thanks,
Joe

**Comment by JoeLametta** [comment]
It think this has been fixed a while ago thanks to [FS#57399](https://bugs.archlinux.org/task/57399).
Please test again: if it's working as expected I think you can safely uncomment the `check()` function block in whipper's PKGBUILD.

Thanks,
Joe

**Comment by shibumi** [comment]
Mhhh I can uncomment the check() function block now, yes. But the check still throws some errors:
```
...................ERROR:whipper.common.accurip:no track AR CRC on non-HTOA track 1
.......ERROR:whipper.common.accurip:could not save entry to /tmp/tmpQ7WeWpwhipper_accurip_cache_test/c/1/2/dBAR-002-0000f21c-00027ef8-05021002.bin: "[Errno 13] Permission denied: '/tmp/tmpQ7WeWpwhipper_accurip_cache_test/c'"
.ERROR:whipper.common.accurip:error retrieving AccurateRip entry: 404 Not Found <Response [404]>
WARNING:whipper.common.accurip:entry not found in AccurateRip database
...WARNING:whipper.program.arc:ARC calculation failed: arc return code is non zero: 1
ERROR:whipper.common.accurip:could not calculate AccurateRip v1 checksum for track 1 '/does/not/exist'
WARNING:whipper.program.arc:ARC calculation failed: arc return code is non zero: 1
ERROR:whipper.common.accurip:could not calculate AccurateRip v2 checksum for track 1 '/does/not/exist'
.............................................................WARNING:whipper.common.mbngs:Release with ID '3451f29c-9bb8-4cc5-bfcc-bd50104b94f8' (Jeff Buckley - Everybody Here Wants You) does not have a date
...............
----------------------------------------------------------------------
Ran 106 tests in 6.669s

OK
```

Are there supposed to be there?

**Comment by JoeLametta** [comment]
> Are there supposed to be there?

I think the `Permission denied` one looks unusual. I'll check if all those are expected to be there...

**Comment by shibumi** [comment]
@JoeLametta Well the check() runs with an "OK", so for me this issue can be closed. I guess the permission problems are there because i run the build in a container.

**Comment by JoeLametta** [comment]
#157.
